server:
  error:
    include-message: always
    include-binding-errors: always


rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartinterview
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop  # Make sure it's 'create-drop' or 'update'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
